package com.ctacorp.syndication

import com.ctacorp.syndication.commons.util.Util
import grails.converters.JSON
import grails.plugins.rest.client.RestBuilder
import grails.transaction.Transactional

@Transactional(readOnly = true)
class TagService {
    def grailsApplication
    def authorizationService

    RestBuilder rest = new RestBuilder()

    def listTags(params = [:]) {
        params.languageId = params.languageId ?: 1
        params.typeId = params.typeId ?: 1
        def offset = params.offset ?: 0
        def max = params.max ?: 10
        def sort = params.sort ?: "id"
        params.name = params.name ?: ""
        if (params.order?.toLowerCase() == "desc") {
            sort = "-${sort}"
        }
        get("/tags.json?languageId=${params.languageId}&typeId=${params.typeId}&includePaginationFields=1&offset=${offset}&max=${max}&sort=${sort}&nameContains=${params.name}")
    }

    def listAllTags(params = [:]) {
        def offset = params.offset ?: 0
        def max = params.max ?: 10
        def sort = params.sort ?: "id"
        params.name = params.name ?: ""
        if (params.order?.toLowerCase() == "desc") {
            sort = "-${sort}"
        }
        get("/tags.json?includePaginationFields=1&offset=${offset}&max=${max}&sort=${sort}&nameContains=${params.name}")
    }

    def findTagsByTagName(String name, params = [:]) {
        params.languageId = params.languageId ?: 1
        params.tagTypeId = params.tagTypeId ?: 1
        get("/tags/findTagsByTagName.json?tagName=${name}&languageId=${params.languageId}&tagTypeId=${params.tagTypeId}")
    }

    def suggestTags(MediaItem mediaItem) {
        def titleParts = mediaItem.name.split(" ").collect { cleanString(it) }
        def suggestions = []
        titleParts.each { part ->
            if(part.size() > 1) {
                if (!(part in TAG_EXCLUSION_LIST)) {
                    suggestions << part
                }
            }
        }
        suggestions.unique()
    }

    def getTag(Long id) {
        get("/tags/show/${id}.json")
    }

    def deleteTag(Long id) {
        delete("/tags/deleteTag/${id}")
    }

    def deleteTagType(Long id) {
        delete("/tagTypes/deleteTagType/${id}")
    }

    def tag(String tagIds, Long mediaId) {
        def url = MediaItem.get(mediaId).sourceUrl
        post("/tags/tagSyndicatedItemByTagIds.json", [syndicationId: mediaId, tagIds: tagIds, url: url])
    }

    def setTags(String tagIds, Long mediaId, params = [:]) {
        tagIds = checkForNewTags(tagIds, params)
        
        def url = MediaItem.get(mediaId).sourceUrl
        params.languageId = params.languageId ?: 1
        params.tagTypeId = params.tagTypeId ?: 1
        post("/tags/setTagsForSyndicatedItemByTagIds.json", [syndicationId: mediaId, tagIds: tagIds, url: url, languageId: params.languageId, tagTypeId: params.tagTypeId])
    }

    def checkForNewTags(tagIds, params) {
        tagIds = tagIds?.split(",")?.collect { String id ->
            if (id && !id.isInteger()) {
                createTag(id.substring(1, id.size() - 1), params.tagTypeId as Long, params.languageId as Long).id
            } else {
                id
            }
        }
        tagIds?.removeAll([null])
        return tagIds?.toString()?.replace("[", "")?.replace("]", "")
    }

    def getTagsForSyndicationId(Long id) {
        get("/tags/getTagsForSyndicationId.json?syndicationId=${id}")
    }

    def getTagsForSyndicationId(Long id, Long languageId, Long tagTypeId) {
        get("/tags/getTagsForSyndicationId.json?syndicationId=${id}&languageId=${languageId}&tagTypeId=${tagTypeId}")
    }

    def createTag(String tagName, Long tagTypeId, Long languageId) {
        post("/tags/findOrSaveTag", [name: tagName, type: tagTypeId, language: languageId])
    }

    def saveTagType(String tagTypeName, String tagTypeDescription) {
        post("/tagTypes/saveTagType", [name: tagTypeName, description: tagTypeDescription])
    }

    def updateTagType(Long tagTypeId, String tagTypeName, String tagTypeDescription) {
        post("/tagTypes/updateTagType", [name: tagTypeName, id: tagTypeId, description: tagTypeDescription])
    }

    def updateTag(Long id, String name, Long languageId, Long tagTypeId) {
        post("/tags/updateTag?languageId=${languageId}&tagTypeId=${tagTypeId}", [name: name, id: id])
    }

    def getTagType(Long id) {
        get("/tagTypes/getTagTypeById/${id}")
    }

    def getTagTypeByName(String name) {
        get("/tags/getTagTypeByName.json?name=${name}")
    }

    def getTagTypes(params = [:]) {
        def include = params.includePaginationFields ?: 0
        def offset = params.offset ?: 0
        def max = params.max ?: 10
        def sort = params.sort ?: "id"
        if (params.order?.toLowerCase() == "desc") {
            sort = "-${sort}"
        }
        get("/tagTypes/index.json?offset=${offset}&max=${max}&sort=${sort}&includePaginationFields=${include}")
    }

    def getTagLanguages(allTags = null) {
        get("/languages.json?allTags=${allTags}")
    }

    def getAllActiveTagLanguages() {
        get("/languages/getActive.json")
    }

    def activateTagLanguage(Long id) {
        post("/languages/activate.json", [languageId: id])
    }

    def deactivateTagLanguage(Long id) {
        post("/languages/deactivate.json", [languageId: id])
    }

    def status() {
        try {
            def status = get("/statusCheck")
            return (status) ? true : false
        } catch (e) {
            return false;
        }
    }

    def tagMultiple(String tagIds, String mediaIds, params = []) {
        def urls = []
        tagIds = checkForNewTags(tagIds, params)
        def mediaIdsAsLongs = mediaIds.split(",").collect { it as Long }.unique()
        mediaIds = mediaIdsAsLongs.join(',')

        mediaIdsAsLongs.each { mediaId ->
            urls << MediaItem.get(mediaId).sourceUrl
        }
        post("/tags/tagSyndicatedItemsByTagIds.json", [syndicationIds: mediaIds, tagIds: tagIds, urls: urls.join(",")])
    }

    /*
        There is a bunch of stuff every media item controller has to do to have the tag widget included.
        This method puts all that logic in one place so it can be reused with maximum dry code.
    */

    def getTagInfoForMediaShowViews(MediaItem mi, params) {

        params.languageId = params.languageId ?: 1
        params.tagTypeId = params.tagTypeId ?: 1

        String tags = getTagsForSyndicationId(mi?.id, params.long('languageId'), params.long('tagTypeId'))?.collect { tag ->
            [id: tag.id, name: tag.name]
        }?.sort { it.name } as JSON

        def languages = getAllActiveTagLanguages()
        def tagTypes = getTagTypes()

        def selectedLanguage = languages.find { "${it.id}" == "${params.languageId}" }?.name
        def selectedTagType = tagTypes.find { "${it.id}" == "${params.tagTypeId}" }?.name

        return [tags: tags, languages: languages, tagTypes: tagTypes, selectedLanguage: selectedLanguage, selectedTagType: selectedTagType]

    }

    private get(String path) {
        try {
            return rest.get(grailsApplication.config.tagCloud.serverAddress + path).json
        } catch (e) {
            log.error "Could not connect to: ${path}"
            return null
        }
    }

    private post(String path, params) {
        try {
            return authorizationService.post(grailsApplication.config.tagCloud.serverAddress + path, params)
        } catch (e) {
            log.error "Could not connect to: ${path}"
            return null
        }
    }

    private delete(String path) {
        try {
            return authorizationService.delete(grailsApplication.config.tagCloud.serverAddress + path)
        } catch (e) {
            log.error "Could not connect to: ${path}"
            return null
        }
    }

    private String gatherPaginationParams(params) {
        String parts = ""
        if (!params) {
            return parts
        }
        parts = "?"
        if (params.sort) {
            parts += "sort=${params.sort}&"
        }
        if (params.order) {
            parts += "order=${params.order}&"
        }
        if (params.max) {
            parts += "max=${params.max}&"
        }
        if (params.offset) {
            parts += "offset=${params.offset}&"
        }
        if (Util.isTrue(params.includePaginationFields, false)) {
            parts += "includePaginationFields=1"
        }
        if (parts == "?") {
            return ""
        }
        if (parts.endsWith("&")) {
            return parts[0..-1 - 1]
        }
        parts
    }

    private String cleanString(input) {
        String cleaned = input
        SYMBOL_EXCLUSION_LIST.each { symbol ->
            if(cleaned.contains(symbol)){
                cleaned = cleaned.replace(symbol, "")
            }
        }
        cleaned = stripNasties(cleaned)
        if(isAcronym(cleaned)){ return cleaned }
        cleaned.toLowerCase()
    }

    private boolean isAcronym(String word){
        boolean longEnough = word.size() >= 2
        if(!longEnough) { return false }
        boolean uppercase = ! word.any{Character.isLowerCase(it as Character)}
        uppercase
    }

    private String stripNasties(String word){
        String cleanedWord = ""
        word.each{
            if(((it as char) as int) <= 127){
                cleanedWord += it
            }
        }
        cleanedWord
    }

    private final static SYMBOL_EXCLUSION_LIST = [
            "'s",
            "’s",
            "’",
            "~",
            "!",
            "@",
            "#",
            "\$",
            "%",
            "^",
            "&",
            "*",
            "(",
            ")",
            "_",
            "+",
            "`",
            "-",
            "=",
            "[",
            "]",
            "\\",
            "{",
            "}",
            "|",
            ";",
            ":",
            "\"",
            ",",
            ".",
            "/",
            "<",
            ">",
            "?",
            "1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "7",
            "8",
            "9",
            "0",
            " "
    ]
    private final static TAG_EXCLUSION_LIST = [
            "are",
            "my",
            "taking",
            "title",
            "county",
            "spread",
            "spreads",
            "starts",
            "soon",
            "fully",
            "extend",
            "reach",
            "preventing",
            "size",
            "often",
            "recommended",
            "focuses",
            "use",
            "it",
            "usually",
            "got",
            "up",
            "down",
            "dont",
            "don't",
            "be",
            "more",
            "than",
            "how",
            "do",
            "get",
            "or",
            "does",
            "keep",
            "about",
            "check",
            "glance",
            "and",
            "using",
            "keeping",
            "find",
            "out",
            "can",
            "stop",
            "related",
            "why",
            "you",
            "your",
            "need",
            "a",
            "abandoned",
            "able",
            "absolute",
            "academic",
            "acceptable",
            "acclaimed",
            "accomplished",
            "accordingly",
            "accurate",
            "aching",
            "acidic",
            "acrobatic",
            "active",
            "actual",
            "addition",
            "additionally",
            "adept",
            "admirable",
            "admired",
            "adolescent",
            "adorable",
            "adored",
            "advanced",
            "adventurous",
            "affectionate",
            "afraid",
            "after",
            "afterwards",
            "aged",
            "aggravating",
            "aggressive",
            "agile",
            "agitated",
            "agonizing",
            "agreeable",
            "ajar",
            "alarmed",
            "alarming",
            "alert",
            "alienated",
            "alive",
            "all",
            "alone",
            "also",
            "alternatively",
            "altruistic",
            "amazing",
            "ambitious",
            "ample",
            "amused",
            "amusing",
            "an",
            "anchored",
            "ancient",
            "angelic",
            "angry",
            "anguished",
            "animated",
            "annoyed",
            "annoying",
            "annual",
            "another",
            "antique",
            "anxious",
            "any",
            "anyway",
            "apprehensive",
            "appropriate",
            "apt",
            "arctic",
            "arid",
            "aromatic",
            "arrogant",
            "artistic",
            "as",
            "ashamed",
            "assured",
            "astonishing",
            "at",
            "athletic",
            "attached",
            "attentive",
            "attractive",
            "austere",
            "authentic",
            "authorized",
            "automatic",
            "avaricious",
            "average",
            "aware",
            "awesome",
            "awful",
            "awkward",
            "babyish",
            "back",
            "bad",
            "baggy",
            "bare",
            "barren",
            "basic",
            "beautiful",
            "because",
            "before",
            "begin",
            "belated",
            "beloved",
            "beneficial",
            "besides",
            "best",
            "better",
            "bewildered",
            "bewitched",
            "big",
            "big-hearted",
            "biodegradable",
            "bite-sized",
            "bitter",
            "black",
            "black-and-white",
            "bland",
            "blank",
            "blaring",
            "bleak",
            "blind",
            "blissful",
            "blond",
            "bloody",
            "blue",
            "blue-eyed",
            "blushing",
            "bogus",
            "boiling",
            "bold",
            "bony",
            "bored",
            "boring",
            "bossy",
            "both",
            "bouncy",
            "bountiful",
            "bowed",
            "brainy",
            "brave",
            "breakable",
            "brief",
            "bright",
            "brilliant",
            "brisk",
            "broken",
            "bronze",
            "brown",
            "bruised",
            "bubbly",
            "bulky",
            "bumpy",
            "buoyant",
            "burdensome",
            "burly",
            "bustling",
            "busy",
            "but",
            "buttery",
            "buzzing",
            "by",
            "calculating",
            "calm",
            "candid",
            "canine",
            "capital",
            "carefree",
            "careful",
            "careless",
            "caring",
            "case",
            "caused",
            "cautious",
            "cavernous",
            "celebrated",
            "charming",
            "cheap",
            "cheerful",
            "cheery",
            "chief",
            "chilly",
            "chubby",
            "circular",
            "circumstances",
            "classic",
            "clean",
            "clear",
            "clear-cut",
            "clever",
            "close",
            "closed",
            "cloudy",
            "clueless",
            "clumsy",
            "cluttered",
            "coarse",
            "cold",
            "colorful",
            "colorless",
            "colossal",
            "combative",
            "comfortable",
            "common",
            "compassionate",
            "competent",
            "complete",
            "complex",
            "complicated",
            "composed",
            "concerned",
            "conclude",
            "concrete",
            "condemned",
            "confused",
            "conscious",
            "consequence",
            "consequently",
            "considerate",
            "constant",
            "content",
            "contrary",
            "contrast",
            "conventional",
            "cooked",
            "cool",
            "cooperative",
            "coordinated",
            "corny",
            "corrupt",
            "costly",
            "courageous",
            "courteous",
            "crafty",
            "crazy",
            "creamy",
            "creative",
            "creepy",
            "criminal",
            "crisp",
            "critical",
            "crooked",
            "crowded",
            "cruel",
            "crushing",
            "cuddly",
            "cultivated",
            "cultured",
            "cumbersome",
            "curious",
            "curly",
            "curvy",
            "cute",
            "cylindrical",
            "damaged",
            "damp",
            "dangerous",
            "dapper",
            "daring",
            "dark",
            "darling",
            "dazzling",
            "dead",
            "deadly",
            "deafening",
            "dear",
            "dearest",
            "decent",
            "decimal",
            "decisive",
            "deep",
            "defeated",
            "defenseless",
            "defensive",
            "defiant",
            "deficient",
            "definite",
            "definitive",
            "delayed",
            "delectable",
            "delicious",
            "delightful",
            "delirious",
            "demanding",
            "dense",
            "dental",
            "dependable",
            "dependent",
            "depressed",
            "descriptive",
            "deserted",
            "despite",
            "detailed",
            "determined",
            "devoted",
            "different",
            "differs",
            "difficult",
            "digital",
            "diligent",
            "dim",
            "dimpled",
            "dimwitted",
            "direct",
            "dirty",
            "disastrous",
            "discrete",
            "disfigured",
            "disguised",
            "disgusted",
            "disgusting",
            "dishonest",
            "disloyal",
            "dismal",
            "distant",
            "distinct",
            "distorted",
            "disturbed",
            "dizzy",
            "dopey",
            "doting",
            "double",
            "doubtful",
            "downright",
            "drab",
            "drafty",
            "dramatic",
            "dreary",
            "droopy",
            "dry",
            "dual",
            "dull",
            "dutiful",
            "e.g.",
            "each",
            "eager",
            "early",
            "earnest",
            "easy",
            "easy-going",
            "ecstatic",
            "edible",
            "educated",
            "effect",
            "eigth",
            "elaborate",
            "elastic",
            "elated",
            "elderly",
            "electric",
            "elegant",
            "elementary",
            "elliptical",
            "elsewhere",
            "embarrassed",
            "embellished",
            "eminent",
            "emotional",
            "empty",
            "enchanted",
            "enchanting",
            "encouraging",
            "end",
            "energetic",
            "enlightened",
            "enormous",
            "enraged",
            "enthusiastic",
            "entire",
            "envious",
            "equal",
            "equatorial",
            "essential",
            "esteemed",
            "ethical",
            "euphoric",
            "even",
            "evergreen",
            "everlasting",
            "every",
            "evil",
            "exalted",
            "example",
            "excellent",
            "excitable",
            "excited",
            "exciting",
            "exemplary",
            "exemplified",
            "exhausted",
            "exotic",
            "expensive",
            "experienced",
            "expert",
            "explaining",
            "extra-large",
            "extra-small",
            "extraneous",
            "extroverted",
            "exuberant",
            "fabulous",
            "fact",
            "failing",
            "faint",
            "fair",
            "faithful",
            "fake",
            "false",
            "familiar",
            "famous",
            "fancy",
            "fantastic",
            "far",
            "far-flung",
            "far-off",
            "faraway",
            "fast",
            "fat",
            "fatal",
            "fatherly",
            "favorable",
            "favorite",
            "fearful",
            "fearless",
            "feisty",
            "feline",
            "female",
            "feminine",
            "few",
            "fickle",
            "fierce",
            "fifth",
            "filthy",
            "finally",
            "fine",
            "finished",
            "firm",
            "first",
            "firsthand",
            "firstly",
            "fitting",
            "fixed",
            "flaky",
            "flamboyant",
            "flashy",
            "flat",
            "flawed",
            "flawless",
            "flickering",
            "flimsy",
            "flippant",
            "flowery",
            "fluffy",
            "fluid",
            "flustered",
            "focused",
            "fond",
            "foolhardy",
            "foolish",
            "for",
            "forceful",
            "forked",
            "formal",
            "forsaken",
            "forthright",
            "fortunate",
            "fourth",
            "fragile",
            "fragrant",
            "frail",
            "frank",
            "frantic",
            "frayed",
            "free",
            "french",
            "frequent",
            "fresh",
            "friendly",
            "frightened",
            "frightening",
            "frigid",
            "frilly",
            "frivolous",
            "frizzy",
            "from",
            "front",
            "frosty",
            "frozen",
            "frugal",
            "fruitful",
            "full",
            "fumbling",
            "functional",
            "funny",
            "furthermore",
            "fussy",
            "fuzzy",
            "gargantuan",
            "gaseous",
            "general",
            "generous",
            "gentle",
            "genuine",
            "giant",
            "giddy",
            "gifted",
            "gigantic",
            "giving",
            "glamorous",
            "glaring",
            "glass",
            "gleaming",
            "gleeful",
            "glistening",
            "glittering",
            "gloomy",
            "glorious",
            "glossy",
            "glum",
            "golden",
            "good",
            "good-natured",
            "gorgeous",
            "graceful",
            "gracious",
            "grand",
            "grandiose",
            "granular",
            "grateful",
            "grave",
            "gray",
            "great",
            "greedy",
            "green",
            "gregarious",
            "grieving",
            "grim",
            "grimy",
            "gripping",
            "grizzled",
            "gross",
            "grotesque",
            "grouchy",
            "grounded",
            "growing",
            "growling",
            "grown",
            "grubby",
            "gruesome",
            "grumpy",
            "guilty",
            "gullible",
            "gummy",
            "hairy",
            "half",
            "hand",
            "handmade",
            "handsome",
            "handy",
            "happy",
            "happy-go-lucky",
            "hard",
            "hard-to-find",
            "harmful",
            "harmless",
            "harmonious",
            "harsh",
            "hasty",
            "hateful",
            "haunting",
            "healthy",
            "heartfelt",
            "hearty",
            "heavenly",
            "heavy",
            "hefty",
            "helpful",
            "helpless",
            "hence",
            "here",
            "hidden",
            "hideous",
            "high",
            "high-level",
            "hilarious",
            "hoarse",
            "hollow",
            "homeless",
            "homely",
            "honest",
            "honorable",
            "honored",
            "hopeful",
            "horrible",
            "hospitable",
            "hot",
            "however",
            "huge",
            "humble",
            "humiliating",
            "humming",
            "humongous",
            "hungry",
            "hurt",
            "hurtful",
            "husky",
            "i.e.",
            "icky",
            "icy",
            "ideal",
            "idealistic",
            "identical",
            "idiotic",
            "idle",
            "idolized",
            "ignorant",
            "ill",
            "ill-fated",
            "ill-informed",
            "illegal",
            "illiterate",
            "illustrious",
            "imaginary",
            "imaginative",
            "immaculate",
            "immaterial",
            "immediate",
            "immense",
            "impartial",
            "impassioned",
            "impeccable",
            "imperfect",
            "imperturbable",
            "impish",
            "impolite",
            "important",
            "impossible",
            "impractical",
            "impressionable",
            "impressive",
            "improbable",
            "impure",
            "in",
            "inborn",
            "include",
            "including",
            "incomparable",
            "incompatible",
            "incomplete",
            "inconsequential",
            "incredible",
            "indeed",
            "indelible",
            "indolent",
            "inexpensive",
            "inexperienced",
            "infamous",
            "infantile",
            "infatuated",
            "inferior",
            "infinite",
            "informal",
            "innocent",
            "inquisitive",
            "insecure",
            "insidious",
            "insignificant",
            "insistent",
            "instance",
            "instead",
            "instructive",
            "insubstantial",
            "intelligent",
            "intent",
            "intentional",
            "interesting",
            "internal",
            "international",
            "intrepid",
            "ironclad",
            "irresponsible",
            "irritating",
            "is",
            "itchy",
            "jaded",
            "jagged",
            "jam-packed",
            "jaunty",
            "jealous",
            "jittery",
            "joint",
            "jolly",
            "jovial",
            "joyful",
            "joyous",
            "jubilant",
            "judicious",
            "juicy",
            "jumbo",
            "jumpy",
            "junior",
            "juvenile",
            "kaleidoscopic",
            "keen",
            "key",
            "kind",
            "kindhearted",
            "kindly",
            "klutzy",
            "knobby",
            "knotty",
            "knowing",
            "knowledgeable",
            "known",
            "kooky",
            "kosher",
            "lame",
            "lanky",
            "large",
            "last",
            "lasting",
            "lastly",
            "late",
            "later",
            "lavish",
            "lawful",
            "lazy",
            "leading",
            "leafy",
            "lean",
            "left",
            "legal",
            "legitimate",
            "let",
            "light",
            "lighthearted",
            "likable",
            "likely",
            "limited",
            "limp",
            "limping",
            "linear",
            "lined",
            "liquid",
            "little",
            "live",
            "lively",
            "livid",
            "loathsome",
            "lone",
            "lonely",
            "long",
            "long-term",
            "loose",
            "lopsided",
            "lost",
            "loud",
            "lovable",
            "lovely",
            "loving",
            "low",
            "loyal",
            "lucky",
            "lumbering",
            "luminous",
            "lumpy",
            "lustrous",
            "luxurious",
            "mad",
            "made-up",
            "magnificent",
            "majestic",
            "major",
            "male",
            "mammoth",
            "married",
            "marvelous",
            "masculine",
            "massive",
            "mature",
            "meager",
            "mealy",
            "mean",
            "meanwhile",
            "measly",
            "meaty",
            "medical",
            "mediocre",
            "medium",
            "meek",
            "mellow",
            "melodic",
            "memorable",
            "menacing",
            "merry",
            "messy",
            "metallic",
            "mild",
            "milky",
            "mindless",
            "miniature",
            "minor",
            "minty",
            "miserable",
            "miserly",
            "misguided",
            "misty",
            "mixed",
            "modern",
            "modest",
            "moist",
            "monstrous",
            "monthly",
            "monumental",
            "moral",
            "moreover",
            "mortified",
            "motherly",
            "motionless",
            "mountainous",
            "muddy",
            "muffled",
            "multicolored",
            "mundane",
            "murky",
            "mushy",
            "musty",
            "muted",
            "mysterious",
            "naive",
            "narrow",
            "nasty",
            "natural",
            "naughty",
            "nautical",
            "near",
            "neat",
            "necessary",
            "needy",
            "negative",
            "neglected",
            "negligible",
            "neighboring",
            "nervous",
            "nevertheless",
            "new",
            "next",
            "nice",
            "nifty",
            "nimble",
            "ninth",
            "nippy",
            "nocturnal",
            "noisy",
            "nonstop",
            "normal",
            "not",
            "notable",
            "noted",
            "noteworthy",
            "novel",
            "now",
            "noxious",
            "numb",
            "nutritious",
            "nutty",
            "obedient",
            "obese",
            "oblong",
            "obnoxious",
            "obvious",
            "occasion",
            "occasional",
            "odd",
            "oddball",
            "of",
            "offbeat",
            "offensive",
            "official",
            "oily",
            "old",
            "old-fashioned",
            "on",
            "once",
            "one",
            "only",
            "open",
            "optimal",
            "optimistic",
            "opulent",
            "orange",
            "orderly",
            "ordinary",
            "organic",
            "original",
            "ornate",
            "ornery",
            "other",
            "otherwise",
            "our",
            "outcome",
            "outgoing",
            "outlandish",
            "outlying",
            "outrageous",
            "outstanding",
            "oval",
            "overcooked",
            "overdue",
            "overjoyed",
            "overlooked",
            "palatable",
            "pale",
            "paltry",
            "panicky",
            "parallel",
            "parched",
            "partial",
            "passionate",
            "past",
            "pastel",
            "peaceful",
            "peppery",
            "perfect",
            "perfumed",
            "periodic",
            "perky",
            "personal",
            "pertinent",
            "pesky",
            "pessimistic",
            "petty",
            "phony",
            "physical",
            "piercing",
            "pink",
            "pitiful",
            "place",
            "plain",
            "plaintive",
            "plastic",
            "playful",
            "pleasant",
            "pleased",
            "pleasing",
            "plump",
            "plush",
            "pointed",
            "pointless",
            "poised",
            "polished",
            "polite",
            "political",
            "poor",
            "popular",
            "portly",
            "posh",
            "positive",
            "possible",
            "potable",
            "powerful",
            "powerless",
            "practical",
            "precious",
            "present",
            "prestigious",
            "pretty",
            "previous",
            "previously",
            "pricey",
            "prickly",
            "primary",
            "prime",
            "pristine",
            "private",
            "prize",
            "probable",
            "productive",
            "profitable",
            "profuse",
            "proper",
            "proud",
            "provided",
            "prudent",
            "punctual",
            "pungent",
            "puny",
            "pure",
            "purple",
            "pushy",
            "putrid",
            "puzzled",
            "puzzling",
            "quaint",
            "qualified",
            "quarrelsome",
            "quarterly",
            "queasy",
            "querulous",
            "questionable",
            "quick",
            "quick-witted",
            "quiet",
            "quintessential",
            "quirky",
            "quixotic",
            "quizzical",
            "radiant",
            "ragged",
            "rapid",
            "rare",
            "rash",
            "rather",
            "raw",
            "ready",
            "real",
            "realistic",
            "reasonable",
            "recent",
            "reckless",
            "rectangular",
            "red",
            "reflecting",
            "regal",
            "regular",
            "reliable",
            "relieved",
            "remarkable",
            "remorseful",
            "remote",
            "repentant",
            "repulsive",
            "required",
            "respect",
            "respectful",
            "respects",
            "responsible",
            "result",
            "revolving",
            "rewarding",
            "rich",
            "right",
            "rigid",
            "ringed",
            "ripe",
            "roasted",
            "robust",
            "rosy",
            "rotating",
            "rotten",
            "rough",
            "round",
            "rowdy",
            "royal",
            "rubbery",
            "ruddy",
            "rude",
            "rundown",
            "runny",
            "rural",
            "rusty",
            "sad",
            "safe",
            "salty",
            "same",
            "sandy",
            "sane",
            "sarcastic",
            "sardonic",
            "satisfied",
            "say",
            "scaly",
            "scarce",
            "scared",
            "scary",
            "scented",
            "scholarly",
            "scientific",
            "scornful",
            "scratchy",
            "scrawny",
            "second",
            "second-hand",
            "secondary",
            "secondly",
            "secret",
            "self-assured",
            "self-reliant",
            "selfish",
            "sentimental",
            "separate",
            "serene",
            "serious",
            "serpentine",
            "seventh",
            "several",
            "severe",
            "shabby",
            "shadowy",
            "shady",
            "shallow",
            "shameful",
            "shameless",
            "sharp",
            "shimmering",
            "shiny",
            "shocked",
            "shocking",
            "shoddy",
            "short",
            "short-term",
            "showy",
            "shrill",
            "shy",
            "sick",
            "silent",
            "silky",
            "silly",
            "silver",
            "similar",
            "simple",
            "simplistic",
            "since",
            "sinful",
            "single",
            "sixth",
            "sizzling",
            "skeletal",
            "skinny",
            "sleepy",
            "slight",
            "slim",
            "slimy",
            "slippery",
            "slow",
            "slushy",
            "small",
            "smart",
            "smiling",
            "smoggy",
            "smooth",
            "smug",
            "snappy",
            "snarling",
            "sneaky",
            "sniveling",
            "snoopy",
            "so",
            "sociable",
            "soft",
            "soggy",
            "solid",
            "somber",
            "some",
            "soon",
            "sophisticated",
            "sore",
            "sorrowful",
            "soulful",
            "soupy",
            "sour",
            "spanish",
            "sparkling",
            "sparse",
            "specific",
            "spectacular",
            "speedy",
            "spherical",
            "spicy",
            "spiffy",
            "spirited",
            "spite",
            "spiteful",
            "splendid",
            "spotless",
            "spotted",
            "spry",
            "square",
            "squeaky",
            "squiggly",
            "stable",
            "staid",
            "stained",
            "stale",
            "standard",
            "starchy",
            "stark",
            "starry",
            "steel",
            "steep",
            "stemmed",
            "sticky",
            "stiff",
            "still",
            "stimulating",
            "stingy",
            "stormy",
            "straight",
            "straightaway",
            "strange",
            "strict",
            "strident",
            "striking",
            "striped",
            "strong",
            "studious",
            "stunning",
            "stupendous",
            "stupid",
            "sturdy",
            "stylish",
            "subdued",
            "submissive",
            "substantial",
            "subtle",
            "suburban",
            "successful",
            "such",
            "sudden",
            "sugary",
            "summation",
            "sunny",
            "super",
            "superb",
            "superficial",
            "superior",
            "supportive",
            "sure-footed",
            "surprised",
            "suspicious",
            "svelte",
            "sweaty",
            "sweet",
            "sweltering",
            "swift",
            "sympathetic",
            "talented",
            "talkative",
            "tall",
            "tame",
            "tan",
            "tangible",
            "tart",
            "tasty",
            "tattered",
            "taut",
            "tedious",
            "teeming",
            "tempting",
            "tender",
            "tense",
            "tenth",
            "tepid",
            "terrible",
            "terrific",
            "testy",
            "thankful",
            "that",
            "the",
            "then",
            "therefore",
            "these",
            "thick",
            "thin",
            "thing",
            "third",
            "thirdly",
            "thirsty",
            "this",
            "thorny",
            "thorough",
            "those",
            "though",
            "thoughtful",
            "thoughtless",
            "threadbare",
            "thrifty",
            "through",
            "thunderous",
            "tidy",
            "tight",
            "time",
            "timely",
            "tinted",
            "tiny",
            "tired",
            "to",
            "torn",
            "total",
            "tough",
            "tragic",
            "trained",
            "traumatic",
            "treasured",
            "tremendous",
            "triangular",
            "tricky",
            "trifling",
            "trim",
            "trivial",
            "troubled",
            "true",
            "trusting",
            "trustworthy",
            "trusty",
            "truthful",
            "tubby",
            "turbulent",
            "twin",
            "ugliest",
            "ugly",
            "ultimate",
            "unacceptable",
            "unaware",
            "uncomfortable",
            "uncommon",
            "unconscious",
            "under",
            "understated",
            "unequaled",
            "uneven",
            "unfinished",
            "unfit",
            "unfolded",
            "unfortunate",
            "unhappy",
            "unhealthy",
            "uniform",
            "unimportant",
            "uninterested",
            "unique",
            "united",
            "unkempt",
            "unknown",
            "unlawful",
            "unless",
            "unlined",
            "unlucky",
            "unnatural",
            "unpleasant",
            "unrealistic",
            "unripe",
            "unruly",
            "unselfish",
            "unsightly",
            "unsteady",
            "unsung",
            "untidy",
            "until",
            "untimely",
            "untried",
            "untrue",
            "unused",
            "unusual",
            "unwelcome",
            "unwieldy",
            "unwilling",
            "unwitting",
            "unwritten",
            "upbeat",
            "upright",
            "upset",
            "upshot",
            "uptight",
            "urban",
            "usable",
            "used",
            "useful",
            "useless",
            "utilized",
            "utter",
            "vacant",
            "vague",
            "vain",
            "valid",
            "valuable",
            "vapid",
            "variable",
            "vast",
            "velvety",
            "venerated",
            "vengeful",
            "verifiable",
            "vibrant",
            "vicious",
            "victorious",
            "vigilant",
            "vigorous",
            "villainous",
            "violent",
            "violet",
            "virtual",
            "virtuous",
            "visible",
            "vital",
            "vivacious",
            "vivid",
            "voluminous",
            "wan",
            "wandering",
            "warlike",
            "warm",
            "warmhearted",
            "warped",
            "wary",
            "wasteful",
            "watchful",
            "waterlogged",
            "watery",
            "wavy",
            "weak",
            "wealthy",
            "weary",
            "webbed",
            "wee",
            "weekly",
            "weepy",
            "weighty",
            "weird",
            "welcome",
            "well",
            "well-documented",
            "well-groomed",
            "well-informed",
            "well-lit",
            "well-made",
            "well-off",
            "well-to-do",
            "well-worn",
            "wet",
            "when",
            "whenever",
            "whereas",
            "which",
            "while",
            "whimsical",
            "whirlwind",
            "whispered",
            "white",
            "whole",
            "whopping",
            "wicked",
            "wide",
            "wide-eyed",
            "wiggly",
            "wild",
            "willing",
            "wilted",
            "winding",
            "windy",
            "winged",
            "wiry",
            "wise",
            "with",
            "without",
            "witty",
            "wobbly",
            "woeful",
            "wonderful",
            "wooden",
            "woozy",
            "words",
            "wordy",
            "worldly",
            "worn",
            "worried",
            "worrisome",
            "worse",
            "worst",
            "worthless",
            "worthwhile",
            "worthy",
            "wrathful",
            "wretched",
            "writhing",
            "wrong",
            "wry",
            "yawning",
            "yearly",
            "yellow",
            "yellowish",
            "yet",
            "young",
            "youthful",
            "yummy",
            "zany",
            "zealous",
            "zesty",
            "zigzag"]
}
