---
grails:
    profile: web
    codegen:
        defaultPackage: tag_cloud
    spring:
        transactionManagement:
            proxies: false
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false

# Spring Actuator Endpoints are Disabled by Default
endpoints:
    enabled: false
#    jmx:
#        enabled: true

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlets: html
                taglib: none
                staticparts: none
endpoints:
    jmx:
        unique-names: true

---
hibernate:
    cache:
        queries: false
        use_second_level_cache: true
        use_query_cache: false
        region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory

dataSource:
    pooled: true
    jmxExport: true
    driverClassName: com.mysql.jdbc.Driver
    dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    logSql: false
    username: "${MYSQL_USER}"
    password: "${MYSQL_PASSWORD}"

environments:
    development:
        dataSource:
            dbCreate: update
            url: "${TAG_CLOUD_DB_URL}"
    test:
        dataSource:
            dbCreate: update
            url: "${TAG_CLOUD_DB_URL}"
    production:
        dataSource:
            dbCreate: update
            url: "${TAG_CLOUD_DB_URL}"
            properties:
                jmxEnabled: true
                initialSize: 5
                maxActive: 50
                minIdle: 5
                maxIdle: 25
                maxWait: 10000
                maxAge: 600000
                timeBetweenEvictionRunsMillis: 5000
                minEvictableIdleTimeMillis: 60000
                validationQuery: SELECT 1
                validationQueryTimeout: 3
                validationInterval: 15000
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: false
                jdbcInterceptors: ConnectionState
                defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED
        grails:
            serverURL: "${TAG_CLOUD_SERVER_URL}"

grails:
    plugin:
        springsecurity:
            securityConfigType : "Annotation"
            userLookup:
                userDomainClassName : 'com.ctacorp.syndication.authentication.User'
                authorityJoinClassName : 'com.ctacorp.syndication.authentication.UserRole'
            authority.className : 'com.ctacorp.syndication.authentication.Role'
            logout:
                postOnly: false
                afterLogoutUrl: "/appInfo/index"
            controllerAnnotations.staticRules :
              - {pattern: '/dbconsole/**', access: ['permitAll']}
              - {pattern: '/**', access: ['permitAll']}
              - {pattern: '/assets/**', access: ['permitAll']}
              - {pattern: '/**/js/**', access: ['permitAll']}
              - {pattern: '/**/css/**', access: ['permitAll']}
              - {pattern: '/**/images/**', access: ['permitAll']}
              - {pattern: '/**/favicon.ico', access: ['permitAll']}
        xframeoptions:
            deny: true