---
grails:
    profile: web
    codegen:
        defaultPackage: syndication_api
    spring:
        transactionManagement:
            proxies: false
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false

# Spring Actuator Endpoints are Disabled by Default
endpoints:
    enabled: false
    jmx:
        enabled: true

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlets: html
                taglib: none
                staticparts: none
endpoints:
    jmx:
        unique-names: true

---
hibernate:
    cache:
        queries: false
        use_second_level_cache: true
        use_query_cache: false
        region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory

dataSource:
  pooled: true
  jmxExport: true
  driverClassName: com.mysql.jdbc.Driver
  dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  logSql: false
  username: "${MYSQL_USER}"
  password: "${MYSQL_PASSWORD}"

environments:
    development:
        dataSource:
            dbCreate: update
            url: jdbc:mysql://localhost/synd3?useSSL=false
    test:
        dataSource:
            dbCreate: update
            url: jdbc:h2:mem:testDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    production:
        dataSource:
            dbCreate: update
            url: "${SYND3_DB_URL}"
            properties:
                jmxEnabled: true
                initialSize: 5
                maxActive: 50
                minIdle: 5
                maxIdle: 25
                maxWait: 10000
                maxAge: 600000
                timeBetweenEvictionRunsMillis: 5000
                minEvictableIdleTimeMillis: 60000
                validationQuery: SELECT 1
                validationQueryTimeout: 3
                validationInterval: 15000
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: false
                jdbcInterceptors: ConnectionState
                defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED
        grails:
            serverURL: "${API_SERVER_URL}"

grails:
  mail:
    host: "${MAIL_HOST}"
    port: ${MAIL_PORT}
  plugin:
    springsecurity:
      useSecurityEventListener : true
      userLookup:
        userDomainClassName : 'com.ctacorp.syndication.authentication.User'
        authorityJoinClassName : 'com.ctacorp.syndication.authentication.UserRole'
        authority.className : 'com.ctacorp.syndication.authentication.Role'
      controllerAnnotations.staticRules :
        - {pattern: '/**', access: ['permitAll']}
        - {pattern: '/index', access: ['permitAll']}
        - {pattern: '/index.gsp', access: ['permitAll']}
        - {pattern: '/swaggerIndex.gsp', access: ['permitAll']}
        - {pattern: '/assets/**', access: ['permitAll']}
        - {pattern: '/**/js/**', access: ['permitAll']}
        - {pattern: '/**/css/**', access: ['permitAll']}
        - {pattern: '/**/images/**', access: ['permitAll']}
        - {pattern: '/**/favicon.ico', access: ['permitAll']}
    aws:
      s3:
        bucket: "syndication-files"
        acl: "private"
      credentials:
        accessKey: "${AWS_ACCESS_KEY}"
        secretKey: "${AWS_SECRET_KEY}"
    xframeoptions:
        deny: true

swaggerGrails:
  swaggerApiVersion: "2.0"
  yourApiVersion: "2"
  yourApiTitle: "HHS Media Services API"
  contact:
      email: "syndicationadmin@hhs.gov"
  license:
      name: "GNU GENERAL PUBLIC LICENSE"
      url: "http://www.gnu.org/licenses/gpl.html"
  termsOfServiceUrl: "http://www.hhs.gov/web/socialmedia/policies/tos.html#ready"
  basePath: "${SYNDICATION_APIPATH}"
  description: <div class="swagger-ui-wrap extraFooter"><h3>Common Features / Behaviors</h3>
                    <div class="features">
                        <ul>
                            <li><strong>* "sort" param:</strong> supports multi column sorting through the use of commas as delimiters, and a hyphen to denote descending order.
                                <br/>
                                <strong><span>Examples:</span></strong>
                                <ul>
                                    <li><span class="example">name</span><span class="description">sort results by name ascending</span></li>
                                    <li><span class="example">-name</span><span class="description">sort results by name descending</span></li>
                                    <li><span class="example">-name,id</span><span class="description">sort results by name descending and then by id ascending</span></li>
                                    <li><span class="example">id,-dateContentAuthored</span><span class="description">sort results by id ascending and then date descending</span></li>
                                </ul>
                            </li>
                            <li><strong>Date formats:</strong> Date input format is expected to be based on <a href="http://www.ietf.org/rfc/rfc3339.txt">RFC 3339</a>. <br/>
                                <span><strong>Example:</strong></span>
                                <ul><li>2013-11-18T18:43:01Z</li></ul>
                            </li>
                        </ul>
                    </div>
                </div>
  scanForDefinition:
      - com.ctacorp.syndication.api
      - com.ctacorp.syndication.marshal
#  pathOrder: "/media"
  tagOrder: "media"
  responseHeader: '{
                     "meta": {
                         "$ref": "#/definitions/Meta"
                       },
                     "callback": { "type": "string" },
                     "results": {
                        "type": "array",
                        "items":{
                        "$ref": '
  responseFooter: '}}}'
