---
grails:
    profile: web
    codegen:
        defaultPackage: syndication_storefront
    spring:
        transactionManagement:
            proxies: false
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false

# Spring Actuator Endpoints are Disabled by Default
endpoints:
    enabled: false
    jmx:
        enabled: true
---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlets: html
                taglib: none
                staticparts: none
endpoints:
    jmx:
        unique-names: true

---
hibernate:
    cache:
        queries: false
        use_second_level_cache: true
        use_query_cache: false
        region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory

dataSource:
   pooled: true
   jmxExport: true
   driverClassName: com.mysql.jdbc.Driver
   dialect: org.hibernate.dialect.MySQL5InnoDBDialect
   logSql: false
   username: "${MYSQL_USER}"
   password: "${MYSQL_PASSWORD}"

environments:
    development:
        dataSource:
            dbCreate: update
            url : jdbc:mysql://localhost/synd3?useSSL=false
        grails:
            serverURL: http://localhost:8088
        recaptcha:
            enabled: true

    test:
        dataSource:
            driverClassName: org.h2.Driver
            dbCreate: update
            url: jdbc:h2:mem:testDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
        grails:
            serverURL: http://localhost:8088

    production:
        dataSource:
            dbCreate: update
            url: "${SYND3_DB_URL}"
            properties:
                jmxEnabled: true
                initialSize: 5
                maxActive: 50
                minIdle: 5
                maxIdle: 25
                maxWait: 10000
                maxAge: 600000
                timeBetweenEvictionRunsMillis: 5000
                minEvictableIdleTimeMillis: 60000
                validationQuery: SELECT 1
                validationQueryTimeout: 3
                validationInterval: 15000
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: false
                jdbcInterceptors: ConnectionState
                defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED
        grails:
            serverURL: "${STOREFRONT_SERVER_URL}"
        recaptcha:
            enabled: true

greenmail:
#  disabled: true
  ports:
    smtp: 3026

grails:
  mail:
    host: "${MAIL_HOST}"
    port: ${MAIL_PORT}
  plugin:
    springsecurity:
      securityConfigType : "Annotation"
      userLookup:
        userDomainClassName : 'com.ctacorp.syndication.authentication.User'
        authorityJoinClassName : 'com.ctacorp.syndication.authentication.UserRole'
        authority.className : 'com.ctacorp.syndication.authentication.Role'
      controllerAnnotations.staticRules :
        - {pattern: '/dbconsole/**', access: ['permitAll']}
        - {pattern: '/**', access: ['permitAll']}
        - {pattern: '/assets/**', access: ['permitAll']}
        - {pattern: '/**/js/**', access: ['permitAll']}
        - {pattern: '/**/css/**', access: ['permitAll']}
        - {pattern: '/**/images/**', access: ['permitAll']}
        - {pattern: '/greenmail/**', access :['permitAll']}
        - {pattern: '/**/favicon.ico', access: ['permitAll']}
    xframeoptions:
        deny: true

management.info.git.mode: full

recaptcha:
    publicKey: "6LcmnyUUAAAAAMaUCcludVqLr6dlCHVZuGQDRLOO"
    privateKey: "6LcmnyUUAAAAACz-NIR6t1PGvAStggoqYtElGadW"
    includeScript: true
    includeNoScript: true
