recaptcha {
    // These keys are generated by the ReCaptcha service
    publicKey = "6Lcc7x0UAAAAACphfW-yF5j0pGeC-j57G5qkTEuB"
    privateKey = "6Lcc7x0UAAAAAPTsVqTFZZlDQgXX2k-uHf3Z2nPm"

    // Include the noscript tags in the generated captcha
    includeNoScript = true
    includeScript = true

    // Force language change. See this for more: http://code.google.com/p/recaptcha/issues/detail?id=133
    forceLanguageInURL = false
}

mailhide {
    // Generated by the Mailhide service
    publicKey = ""
    privateKey = ""
}

environments {
    development {
        recaptcha {
            // Set to false to disable the display of captcha
            enabled = true

            // Communicate using HTTPS
            useSecureAPI = false
        }
    }
    production {
        recaptcha {
            // Set to false to disable the display of captcha
            enabled = true

            // Communicate using HTTPS
            useSecureAPI = true
        }
    }
}

environments {
    production {
        server {
            session {
                cookie {
                    domain = System.getenv('STOREFRONT_SERVER_URL').split('/')[2]
                    setProperty "http-only", true
                    path = '/'
                    secure = true
                }
            }
        }
    }
}