recaptcha {
    // These keys are generated by the ReCaptcha service
    publicKey = "6Le-29USAAAAAH6E6cNmxmcA4XdcYd6Z7_B64CIW"
    privateKey = "6Le-29USAAAAAB84uD8YnQaeos0e_RXyHBtzm__q"

    // Include the noscript tags in the generated captcha
    includeNoScript = true

    // Force language change. See this for more: http://code.google.com/p/recaptcha/issues/detail?id=133
    forceLanguageInURL = false
}

mailhide {
    // Generated by the Mailhide service
    publicKey = ""
    privateKey = ""
}

environments {
    development {
        recaptcha {
            // Set to false to disable the display of captcha
            enabled = false

            // Communicate using HTTPS
            useSecureAPI = false
        }
    }
    production {
        recaptcha {
            // Set to false to disable the display of captcha
            enabled = true

            // Communicate using HTTPS
            useSecureAPI = true
        }
    }
}